# Generated by Django 4.1.2 on 2022-10-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hourly_rate', models.FloatField()),
                ('employee_id', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartialTeamEmployeeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('LEADER', 'Leader')], default='EMPLOYEE', max_length=20)),
                ('work_arr', models.PositiveIntegerField(default=40, verbose_name='Work Arrangements [hours/week]')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.team')),
            ],
            options={
                'unique_together': {('employee', 'team')},
            },
        ),
    ]
